server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3305/second_hand?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

mybatis:
  type-aliases-package: com.example.market.entity
  configuration:
    map-underscore-to-camel-case: true